# 使用Node.js作为基础镜像
ARG NODE_VERSION=18.14.2

FROM node:${NODE_VERSION}-slim as base

# 添加环境变量
ENV AWS_ACCESS_KEY_ID=
ENV AWS_SECRET_ACCESS_KEY=
ENV IMAGE_PREVIEW_URI=
ENV JWT_SECRET_KEY=
ENV MY_MONGODB_URI=
ENV ORAMA_API_KEY=
ENV ORAMA_API_URL=
ENV UMAMI_ADDRESS=
ENV UMAMI_AUTH_TOKEN=
ENV UMAMI_WEBSITE_ID=
ENV MINIO_ENDPOINT=
ENV MINIO_ACCESS_KEY=
ENV MINIO_SECRET_KEY=
ENV MINIO_BUCKET_NAME=

ADD .output /.output

EXPOSE 3000

WORKDIR /.output

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

CMD ["node", "/.output/server/index.mjs"]